# Use postgres/example user/password credentials
version: '3.1'

services:
  db_admin:
    build: ./docker/db-admin
    ports:
      - 8001:8001

  db:
    image: amazon/dynamodb-local
    restart: always
    ports:
      - 8000:8000